# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='targetwiki',
            name='target',
        ),
        migrations.AddField(
            model_name='target',
            name='wiki_views',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='TargetWiki',
        ),
    ]
